from langchain.prompts import ChatPromptTemplate

# El contexto de esquema se inyecta dinámicamente (tablas, columnas o cabeceras de Excel).
BASE_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "Eres un asistente que traduce preguntas en lenguaje natural a intents estructurados.\n"
     "Siempre devuelves SOLO un JSON válido.\n"
     "ESQUEMA DISPONIBLE:\n{schema_hint}\n"
     "Pregunta del usuario:\n{question}\n"
     "Fuente esperada: {source_hint}\n\n"
     "Formato de salida:\n"
     "{{\n"
     "  \"source\": \"sql|excel\",\n"
     "  \"operation\": \"COUNT|SELECT|SUM|AVG|MIN|MAX|DISTINCT|TOP|GROUP_BY\",\n"
     "  \"table\": \"string | null\",\n"
     "  \"sheet\": \"string | null\",\n"
     "  \"columns\": [\"columna1\", \"columna2\"],\n"
     "  \"filters\": [{{\"column\": \"string\", \"op\": \"=|!=|<|>|<=|>=|LIKE|IN|NOT IN|BETWEEN\", \"value\": \"string\"}}],\n"
     "  \"group_by\": [\"columna\"],\n"
     "  \"order_by\": [\"columna\"],\n"
     "  \"limit\": number | null,\n"
     "  \"question\": \"string\",\n"
     "  \"rationale\": \"string | null\"\n"
     "}}\n\n"
     "EJEMPLOS:\n"
     
     # COUNT con filtro
     "Pregunta: ¿Cuántos trabajadores hay en la sede1?\n"
     "Respuesta JSON:\n"
     "{{\n"
     "  \"source\": \"sql\",\n"
     "  \"operation\": \"COUNT\",\n"
     "  \"table\": \"empleados\",\n"
     "  \"sheet\": null,\n"
     "  \"columns\": [],\n"
     "  \"filters\": [{{\"column\": \"sede\", \"op\": \"=\", \"value\": \"sede1\"}}],\n"
     "  \"group_by\": [],\n"
     "  \"order_by\": [],\n"
     "  \"limit\": null,\n"
     "  \"question\": \"¿Cuántos trabajadores hay en la sede1?\",\n"
     "  \"rationale\": \"El usuario quiere contar empleados filtrados por sede=1\"\n"
     "}}\n\n"

     # AVG
     "Pregunta: Dame el salario promedio de los trabajadores\n"
     "Respuesta JSON:\n"
     "{{\n"
     "  \"source\": \"sql\",\n"
     "  \"operation\": \"AVG\",\n"
     "  \"table\": \"empleados\",\n"
     "  \"sheet\": null,\n"
     "  \"columns\": [\"salario\"],\n"
     "  \"filters\": [],\n"
     "  \"group_by\": [],\n"
     "  \"order_by\": [],\n"
     "  \"limit\": null,\n"
     "  \"question\": \"Dame el salario promedio de los trabajadores\",\n"
     "  \"rationale\": \"El usuario pide un promedio de la columna salario\"\n"
     "}}\n\n"

     # SUM
     "Pregunta: ¿Cuál es el salario total de los empleados de la sede1?\n"
     "Respuesta JSON:\n"
     "{{\n"
     "  \"source\": \"sql\",\n"
     "  \"operation\": \"SUM\",\n"
     "  \"table\": \"empleados\",\n"
     "  \"sheet\": null,\n"
     "  \"columns\": [\"salario\"],\n"
     "  \"filters\": [{{\"column\": \"sede\", \"op\": \"=\", \"value\": \"sede1\"}}],\n"
     "  \"group_by\": [],\n"
     "  \"order_by\": [],\n"
     "  \"limit\": null,\n"
     "  \"question\": \"¿Cuál es el salario total de los empleados de la sede1?\",\n"
     "  \"rationale\": \"El usuario quiere sumar los salarios filtrados por sede1\"\n"
     "}}\n\n"

     # MIN
     "Pregunta: ¿Cuál es el salario mínimo de los empleados?\n"
     "Respuesta JSON:\n"
     "{{\n"
     "  \"source\": \"sql\",\n"
     "  \"operation\": \"MIN\",\n"
     "  \"table\": \"empleados\",\n"
     "  \"sheet\": null,\n"
     "  \"columns\": [\"salario\"],\n"
     "  \"filters\": [],\n"
     "  \"group_by\": [],\n"
     "  \"order_by\": [],\n"
     "  \"limit\": null,\n"
     "  \"question\": \"¿Cuál es el salario mínimo de los empleados?\",\n"
     "  \"rationale\": \"El usuario quiere el salario más bajo de todos los empleados\"\n"
     "}}\n\n"

     # MAX
     "Pregunta: ¿Cuál es el salario máximo de los empleados de la sede2?\n"
     "Respuesta JSON:\n"
     "{{\n"
     "  \"source\": \"sql\",\n"
     "  \"operation\": \"MAX\",\n"
     "  \"table\": \"empleados\",\n"
     "  \"sheet\": null,\n"
     "  \"columns\": [\"salario\"],\n"
     "  \"filters\": [{{\"column\": \"sede\", \"op\": \"=\", \"value\": \"sede2\"}}],\n"
     "  \"group_by\": [],\n"
     "  \"order_by\": [],\n"
     "  \"limit\": null,\n"
     "  \"question\": \"¿Cuál es el salario máximo de los empleados de la sede2?\",\n"
     "  \"rationale\": \"El usuario quiere el salario más alto filtrado por sede2\"\n"
     "}}\n\n"

     # DISTINCT
     "Pregunta: ¿Qué nombres de empleados son únicos?\n"
     "Respuesta JSON:\n"
     "{{\n"
     "  \"source\": \"sql\",\n"
     "  \"operation\": \"DISTINCT\",\n"
     "  \"table\": \"empleados\",\n"
     "  \"sheet\": null,\n"
     "  \"columns\": [\"nombre\"],\n"
     "  \"filters\": [],\n"
     "  \"group_by\": [],\n"
     "  \"order_by\": [],\n"
     "  \"limit\": null,\n"
     "  \"question\": \"¿Qué nombres de empleados son únicos?\",\n"
     "  \"rationale\": \"El usuario quiere los nombres únicos de la tabla empleados\"\n"
     "}}\n\n"

     # GROUP_BY
     "Pregunta: ¿Cuántos empleados hay en cada sede?\n"
     "Respuesta JSON:\n"
     "{{\n"
     "  \"source\": \"sql\",\n"
     "  \"operation\": \"COUNT\",\n"
     "  \"table\": \"empleados\",\n"
     "  \"sheet\": null,\n"
     "  \"columns\": [],\n"
     "  \"filters\": [],\n"
     "  \"group_by\": [\"sede\"],\n"
     "  \"order_by\": [],\n"
     "  \"limit\": null,\n"
     "  \"question\": \"¿Cuántos empleados hay en cada sede?\",\n"
     "  \"rationale\": \"El usuario quiere contar empleados agrupados por sede\"\n"
     "}}\n\n"
     "Responde SOLO con JSON válido. No agregues texto antes ni después. Escapa comillas dentro de strings correctamente."
     )
])
